/- Current-paper-only dependency audit.  No project axiom is permitted. -/

import AccessOrthogonality.CurrentPaperTheoremMap

#print axioms AccessOrthogonality.CurrentPaper.characterizationPaperClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.flat_welfare_counterexample
#print axioms AccessOrthogonality.CurrentPaper.mechanismFamiliesClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.fullSeparationClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.independenceClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.bundledRentClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.bertrandClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.verificationBindingClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.welfareCorollaryClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.thm_longrun

#print axioms AccessOrthogonality.CurrentPaper.thm_separation_derivative_zero
#print axioms AccessOrthogonality.CurrentPaper.profit_derivative_zero
#print axioms AccessOrthogonality.CurrentPaper.marginal_lobbying_chain_rule
#print axioms AccessOrthogonality.CurrentPaper.lobbying_foc_of_stationary
#print axioms AccessOrthogonality.CurrentPaper.bundled_policy_dependence_witness
#print axioms AccessOrthogonality.CurrentPaper.bundledExampleObjective_matches_regulator
#print axioms AccessOrthogonality.CurrentPaper.bertrand_fee_eq_marginal_cost
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_policy_matches_selectedPolicy
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_policy_matches_selectedPolicy
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_actual_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_actual_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_equilibrium_selected_policy
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_equilibrium_selected_policy
#print axioms AccessOrthogonality.CurrentPaper.positive_effort_has_profitable_zero_deviation
#print axioms AccessOrthogonality.CurrentPaper.zeroLobbying_unique_nash

/- Atomic schema-2 manuscript roots and exact displayed-formula consumers. -/
#print axioms AccessOrthogonality.CurrentPaper.paper_access_vector_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_quality_growth_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_access_structure_definition_exact
#print axioms AccessOrthogonality.CurrentPaper.totalWelfare
#print axioms AccessOrthogonality.CurrentPaper.paper_provider_objective_exact
#print axioms AccessOrthogonality.CurrentPaper.Regime.mk
#print axioms AccessOrthogonality.CurrentPaper.paper_global_ownership_invariance_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_local_ownership_invariance_exact
#print axioms AccessOrthogonality.CurrentPaper.global_constant_allocation_has_zero_derivatives
#print axioms AccessOrthogonality.CurrentPaper.FunctionalLocalIdentification.mk
#print axioms AccessOrthogonality.CurrentPaper.paper_reduced_welfare_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_characterization_formula_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_equilibrium_reduced_welfare_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_welfare_chain_rule_exact
#print axioms AccessOrthogonality.CurrentPaper.paper_cost_minimizing_branch_exact
#print axioms AccessOrthogonality.CurrentPaper.prop_four_mechanisms_Malpha_with_selection
#print axioms AccessOrthogonality.CurrentPaper.prop_four_mechanisms_Mbeta
#print axioms AccessOrthogonality.CurrentPaper.prop_four_mechanisms_Mgamma
#print axioms AccessOrthogonality.CurrentPaper.prop_four_mechanisms_Mdelta
#print axioms AccessOrthogonality.CurrentPaper.separationFromSC3Claim_proved
#print axioms AccessOrthogonality.CurrentPaper.CredenceGoodAssumption.mk
#print axioms AccessOrthogonality.CurrentPaper.reputation_aggregation_paper_claim
#print axioms AccessOrthogonality.CurrentPaper.paper_consumer_information_exact
#print axioms AccessOrthogonality.CurrentPaper.BundledCertificationAssumption.mk
#print axioms AccessOrthogonality.CurrentPaper.CertifierCompetitionAssumption.mk
#print axioms AccessOrthogonality.CurrentPaper.paper_positive_welfare_incidence_exact
#print axioms AccessOrthogonality.CurrentPaper.cor_t4_welfare_paper
#print axioms AccessOrthogonality.CurrentPaper.bundled_path_unique_witness
#print axioms AccessOrthogonality.CurrentPaper.bundled_equilibrium_ownership_dependence
#print axioms AccessOrthogonality.CurrentPaper.marginal_lobbying_under_zero_profit
