/- Current-paper-only dependency audit.  No project axiom is permitted. -/

import AccessOrthogonality.CurrentPaperTheoremMap

#print axioms AccessOrthogonality.CurrentPaper.characterizationPaperClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.flat_welfare_counterexample
#print axioms AccessOrthogonality.CurrentPaper.mechanismFamiliesClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.fullSeparationClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.independenceClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.bundledRentClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.bertrandClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.verificationBindingClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.welfareCorollaryClaim_proved
#print axioms AccessOrthogonality.CurrentPaper.thm_longrun

#print axioms AccessOrthogonality.CurrentPaper.thm_separation_derivative_zero
#print axioms AccessOrthogonality.CurrentPaper.profit_derivative_zero
#print axioms AccessOrthogonality.CurrentPaper.marginal_lobbying_chain_rule
#print axioms AccessOrthogonality.CurrentPaper.lobbying_foc_of_stationary
#print axioms AccessOrthogonality.CurrentPaper.bundled_policy_dependence_witness
#print axioms AccessOrthogonality.CurrentPaper.bundledExampleObjective_matches_regulator
#print axioms AccessOrthogonality.CurrentPaper.bertrand_fee_eq_marginal_cost
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_policy_matches_selectedPolicy
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_policy_matches_selectedPolicy
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_actual_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_actual_lobbying_best_response
#print axioms AccessOrthogonality.CurrentPaper.bundled_private_equilibrium_selected_policy
#print axioms AccessOrthogonality.CurrentPaper.bundled_public_equilibrium_selected_policy
#print axioms AccessOrthogonality.CurrentPaper.positive_effort_has_profitable_zero_deviation
#print axioms AccessOrthogonality.CurrentPaper.zeroLobbying_unique_nash
